name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven Tests with env variables
      - name: Run API Tests
        env:
          BASE_URI: ${{ secrets.BASE_URI }}
          BEARER_TOKEN: ${{ secrets.API_TOKEN }}
        run: mvn clean test -Dtest="com.grocerystore.api.runners.RunCucumberTest"

      # Upload Cucumber HTML Report (if you generate it under target/)
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/
